#ifndef EDB_ERRORS_H
#define EDB_ERRORS_H

#define EDB_ERROR_FILE_OPEN (1001)
#define EDB_ERROR_FILE_SIZE (1002)
#define EDB_ERROR_OPEN_TXN (1003)
#define EDB_ERROR_READ_ONLY (1004)
#define EDB_ERROR_ALREADY_OPEN (1005)

#define EDB_ERR_IO_FILE_OPEN (2001)
#define EDB_ERR_IO_FILE_SIZE (2002)
#define EDB_ERR_IO_SIZE_MAX (2003)

#define EDB_ERROR_DATA_CORRUPT (1901)
#define EDB_ERROR_DATA_READONLY (1902)

#define ERR_EDB_DB_SIZE_MAX (1003)

#define EDB_ERR_PAGE_FULL (3152)
#define EDB_ERR_PAGE_OUT_OF_BOUNDS (3101)
#define EDB_ERR_PAGE_TOO_LARGE (3102)

#define ERR_ARRAY_INDEX_OUT_OF_BOUNDS (3201)

#define EDB_ERR_TXN_NO_TRANSACTION (2001)
#define EDB_ERR_TXN_INVALID_BLOCK (2003)
#define EDB_ERR_TXN_NOT_IMPLEMENTED (2099)

#endif
